# docker-compose up
# docker-compose down

version: '3'
services:
    app:
        build:
            context: .
            dockerfile: app.Dockerfile
        ports:
            - 8081:80
        volumes:
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./app:/var/www/html